# Usa la imagen oficial de Ubuntu como base
FROM ubuntu:latest

# Etiqueta para identificar al mantenedor de la imagen
LABEL maintainer="tu_email@example.com"

# Crea un archivo de texto en la raíz del sistema
RUN touch /hello.txt

# Comando por defecto al ejecutar el contenedor
CMD ["bash"]
